version: '3.8'
services:
  api:
    build: .
    restart: always
    ports:
      - 3000:3000
    tty: true
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: moviedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/data/db
      - ./sqldump/moviedb_movie.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  dbdata:
